language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=latest
    - WP_VERSION=4.1
    - WP_VERSION=4.0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - make lint
    - make phpunit
